### ISSUE TITLE
srt "--->" 格式无法识别

### ISSUE THREAD

**Issue by mu-tookilt** [YDX-2147483647/Jianying-to-srt#1]
simple_srt.py:16 将 ' ---> ' 更改为 ' --> ' 后导出的 srt 格式在 premiere CC 21版本中可识别，否则会显示 srt 文件头错误

**Comment by YDX-2147483647** [comment]
非常感谢！我之前也遇到这个问题，但有时可以有时不行，一直不清楚是怎么回事。（有段时间以为是因为起始编号（0还是1），改了之后还是不行）
