### ISSUE TITLE
如果是没有视频轨的项目会在这一行报错

### ISSUE THREAD

**Issue by owen8877** [YDX-2147483647/Jianying-to-srt#4]
https://github.com/YDX-2147483647/Jianying-to-srt/blob/d27975dd49f5df4af362a2b8cad2ed0d5c140e87/draft_content.py#L29

不太清楚为什么读视频轨的名字……好像后面也没有用到（我觉得直接返回一个空串也可以跑x

**Comment by YDX-2147483647** [comment]
我翻了翻，以前默认文件名是第一个视频的名称，所以需要……（现在改成项目名了）╮(╯_╰)╭

我一会儿改改。

**Comment by YDX-2147483647** [comment]
// 偶然发现这是凌晨 4:42 发的……注意身体。（虎年大吉）

**Comment by owen8877** [comment]
时区问题而已（观察真敏锐啊
